import { TopicCard } from "./blueprint-engine";

export const TOPICS_MODERN_2025: TopicCard[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // RAG PIPELINES & VECTOR SEARCH (High-Demand 2025/2026 Academic Projects)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "rag-multimodal-pdf-llamaindex",
    letter: "M",
    title: "Multimodal PDF RAG with LlamaIndex and ChromaDB",
    category: "AIML",
    difficulty: 3,
    buildTimeDays: "3–4 days",
    trending: true,
    tagline: "Chat with complex PDFs containing tables, charts, diagrams, and text.",
    whatItDoes: "Traditional RAG only reads plain text. This project builds a multimodal RAG pipeline that extracts tables, flowcharts, and technical figures from PDF documents. It creates vector embeddings using ChromaDB and CLIP/BGE-visual models. Users can ask questions like 'Compare Q3 revenue in Table 2 with Figure 4' and get accurate answers with exact page citations.",
    realWorldUse: "Used by research labs, consulting firms like McKinsey, and engineering teams to parse complex hardware datasheets and annual financial reports without manual reading.",
    examinerExpects: [
      "Explain how multimodal embeddings differ from text-only embeddings.",
      "Show how tables and charts are isolated using visual document parsing.",
      "Explain top-k similarity search and cosine distance in ChromaDB.",
      "Demonstrate live PDF upload with table-aware question answering.",
    ],
    freeVivaQuestions: [
      "Why do traditional text chunkers fail on multi-column PDF tables?",
      "How does LlamaIndex handle metadata filtering during vector retrieval?",
    ],
    freeStep1Title: "Install LlamaIndex, ChromaDB, PyMuPDF, and FastAPI backend",
    datasetName: "Curated technical research PDFs and annual corporate reports",
  },
  {
    id: "rag-graph-knowledge-medical",
    letter: "G",
    title: "GraphRAG: Knowledge Graph-Augmented Medical Assistant",
    category: "AIML",
    difficulty: 4,
    buildTimeDays: "4–5 days",
    trending: true,
    tagline: "Combines vector similarity with Neo4j knowledge graphs to prevent medical hallucinations.",
    whatItDoes: "Standard vector RAG often misses indirect multi-hop relationships between diseases, genes, and drugs. This project constructs a medical knowledge graph in Neo4j and queries it alongside dense vector search (GraphRAG). When a user asks a clinical question, the system traverses interconnected disease nodes to retrieve exact medical pathways with zero hallucinations.",
    realWorldUse: "Pharmaceutical research firms like Pfizer and hospitals use GraphRAG to cross-reference drug interactions and clinical trial side-effects.",
    examinerExpects: [
      "Explain the limitation of pure vector retrieval in multi-hop entity reasoning.",
      "Demonstrate entity and relation extraction from medical clinical summaries.",
      "Show Cypher queries executed dynamically on Neo4j database.",
      "Explain how hallucination rates are measured and reduced.",
    ],
    freeVivaQuestions: [
      "What is the difference between GraphRAG and standard vector RAG?",
      "How do you resolve entity ambiguity when multiple medical synonyms exist?",
    ],
    freeStep1Title: "Set up Neo4j graph database instance and LangChain graph QA chain",
    datasetName: "PubMed Central medical abstracts and drug-disease interaction dataset",
  },
  {
    id: "rag-indian-legal-bns-citations",
    letter: "I",
    title: "Indian Legal AI RAG: Bharatiya Nyaya Sanhita (BNS) Assistant",
    category: "NLP",
    difficulty: 3,
    buildTimeDays: "3–4 days",
    trending: true,
    tagline: "Legal AI assistant that maps old IPC sections to new BNS codes with legal citations.",
    whatItDoes: "With India transitioning from IPC (Indian Penal Code) to BNS (Bharatiya Nyaya Sanhita), lawyers and law students struggle to cross-reference sections. This project creates a specialized legal RAG assistant with hybrid BM25 lexical search and dense embeddings. Users type a crime scenario in plain English, and the system cites the exact BNS section, corresponding old IPC section, and punishment guidelines.",
    realWorldUse: "Legal-tech startups and district courts use automated legal retrieval assistants to draft FIR summaries and bail petition briefs rapidly.",
    examinerExpects: [
      "Explain why hybrid search (BM25 + Dense Vectors) is essential for legal documents.",
      "Demonstrate cross-mapping between old IPC sections and new BNS provisions.",
      "Explain the chunking strategy used for legal clauses and sub-sections.",
      "Show live query answering with exact statutory references.",
    ],
    freeVivaQuestions: [
      "Why does dense vector search alone struggle with exact section numbers like Section 302?",
      "How do you ensure the legal bot does not give fabricated case precedents?",
    ],
    freeStep1Title: "Ingest Bharatiya Nyaya Sanhita (BNS) and Bharatiya Nagarik Suraksha Sanhita (BNSS) gazette PDFs",
    datasetName: "Official BNS, BNSS, and Indian Penal Code statutory gazette texts",
  },
  {
    id: "rag-corrective-crag-hallucination",
    letter: "C",
    title: "Corrective RAG (CRAG) with Automated Hallucination Guardrails",
    category: "AIML",
    difficulty: 4,
    buildTimeDays: "4–5 days",
    trending: true,
    tagline: "Self-evaluating RAG pipeline that triggers web search fallback when confidence is low.",
    whatItDoes: "In standard RAG, if the retrieved document is irrelevant, the LLM hallucinates an incorrect answer. This project implements Corrective RAG (CRAG). An automated evaluator grades the relevance of retrieved chunks. If relevance score is high, it generates the response; if low, it automatically falls back to Tavily web search; if ambiguous, it performs knowledge refinement.",
    realWorldUse: "Enterprise customer service and compliance portals where giving an unverified or outdated answer results in severe business liabilities.",
    examinerExpects: [
      "Explain the 3-state evaluation logic in Corrective RAG (Correct, Ambiguous, Incorrect).",
      "Show how chunk relevance is scored using an auxiliary evaluator model.",
      "Demonstrate dynamic fallback to live internet search when local docs lack information.",
      "Explain how hallucination guardrails (NeMo Guardrails or G-Eval) verify factual accuracy.",
    ],
    freeVivaQuestions: [
      "What is the difference between Self-RAG and Corrective RAG (CRAG)?",
      "How do you prevent web search results from poisoning your enterprise answer?",
    ],
    freeStep1Title: "Build chunk evaluator scoring module and Tavily/DuckDuckGo fallback tool",
    datasetName: "Enterprise policy handbooks and technical documentation benchmark",
  },
  {
    id: "rag-campus-exam-hybrid-search",
    letter: "C",
    title: "Campus Syllabus & Previous Exam Paper RAG System",
    category: "NLP",
    difficulty: 2,
    buildTimeDays: "2–3 days",
    trending: true,
    tagline: "Students upload university syllabus and past 5-year question papers for instant answers.",
    whatItDoes: "College students spend hours hunting for unit-wise questions and textbook answers before exams. This project builds a campus study assistant using hybrid search over university syllabi, lecture notes, and past 5-year exam papers. Students ask questions like 'What are the 10-mark questions frequently asked from Unit 3?' and receive structured answers with reference textbook chapters.",
    realWorldUse: "Colleges and edtech platforms like Chegg and Unacademy use campus Q&A bots to automate academic doubts for thousands of students.",
    examinerExpects: [
      "Explain why hybrid retrieval improves question answering over academic course notes.",
      "Demonstrate unit-wise filtering using vector database metadata tags.",
      "Show live demo answering a 5-mark conceptual engineering question.",
      "Explain how response generation is restricted to university prescribed textbooks.",
    ],
    freeVivaQuestions: [
      "How do you organize document chunks by academic units and module numbers?",
      "What embedding model is best suited for academic technical definitions?",
    ],
    freeStep1Title: "Scaffold Next.js frontend with FastAPI backend and ChromaDB storage",
    datasetName: "University engineering syllabus PDF and previous 5-year exam papers",
  },
  {
    id: "rag-codebase-ast-analyzer",
    letter: "E",
    title: "Enterprise Codebase RAG: Natural Language Repository Explorer",
    category: "FullStack",
    difficulty: 3,
    buildTimeDays: "3–4 days",
    trending: true,
    tagline: "Explore huge GitHub repositories using AST code chunking and natural language questions.",
    whatItDoes: "Navigating a legacy codebase with hundreds of files is overwhelming for new developers. Standard text chunkers break function declarations and class definitions in half. This project uses Abstract Syntax Trees (Tree-sitter) to chunk code logically by functions, classes, and import graphs. Developers ask questions like 'Where is user payment verified?' and get exact code links with call graphs.",
    realWorldUse: "Developer tools like GitHub Copilot Workspace, Cursor, and Sourcegraph use AST-aware RAG to index multi-million-line code repositories.",
    examinerExpects: [
      "Explain why AST (Abstract Syntax Tree) chunking is superior to fixed-character chunking for code.",
      "Demonstrate function call-graph tracking and dependency extraction.",
      "Show semantic search mapping natural language queries to exact Python/TypeScript functions.",
      "Explain how security tokens and secrets are redacted before embedding.",
    ],
    freeVivaQuestions: [
      "What is Tree-sitter and how does it parse multiple programming languages?",
      "How do you represent cross-file dependencies in a code vector database?",
    ],
    freeStep1Title: "Configure Tree-sitter parser for Python and TypeScript repositories",
    datasetName: "Open-source GitHub full-stack repository with API documentation",
  },
  {
    id: "rag-financial-earnings-table-parser",
    letter: "F",
    title: "Financial Earnings Call RAG with SEC-10K Table Extraction",
    category: "Fintech",
    difficulty: 3,
    buildTimeDays: "3–4 days",
    trending: true,
    tagline: "Extracts financial KPIs, balance sheets, and guidance from quarterly earnings reports.",
    whatItDoes: "Financial balance sheets contain dense numerical tables that become scrambled when converted to raw text. This project uses layout-aware markdown table parsing (Unstructured / Table Transformer) to preserve table grid structure. It enables financial analysts to query EBITDA, debt-to-equity ratios, and forward guidance across multi-year quarterly earnings filings.",
    realWorldUse: "Used by hedge funds, credit rating agencies, and fintech platforms to analyze company balance sheets in seconds rather than days.",
    examinerExpects: [
      "Explain how Markdown tables preserve column-row relationships in vector embeddings.",
      "Show how numerical queries like 'Calculate percentage change in net profit' are evaluated.",
      "Demonstrate side-by-side comparison of two fiscal year reports.",
      "Explain citation highlighting for auditing and compliance.",
    ],
    freeVivaQuestions: [
      "Why do LLMs frequently make arithmetic errors when extracting numbers from raw text?",
      "How do you embed tables so that column headers remain associated with data cells?",
    ],
    freeStep1Title: "Set up Table-Transformer and markdown serializer for financial PDF tables",
    datasetName: "Public SEC-10K annual filings and quarterly earnings press releases",
  },
  {
    id: "rag-offline-local-ollama-docs",
    letter: "P",
    title: "100% Offline Private Document RAG with Ollama and Mistral-7B",
    category: "AIML",
    difficulty: 2,
    buildTimeDays: "2–3 days",
    trending: true,
    tagline: "Zero cloud APIs. Complete private document search running locally on student laptops.",
    whatItDoes: "Many defense, healthcare, and enterprise organizations forbid sending confidential documents to external cloud APIs like OpenAI. This project implements a 100% local, offline RAG system using Ollama with quantized Mistral-7B/LLaMA-3 and local ChromaDB. Documents never leave the computer, ensuring absolute data sovereignty and zero API costs.",
    realWorldUse: "Hospitals, defense agencies, and patent attorneys use offline local LLM architectures to analyze sensitive records without data breach risks.",
    examinerExpects: [
      "Demonstrate zero external network calls during document ingestion and inference.",
      "Explain 4-bit and 8-bit quantization (GGUF format) for running LLMs on consumer hardware.",
      "Show local embedding generation using sentence-transformers (e.g., all-MiniLM-L6-v2).",
      "Explain response latency and GPU vs CPU RAM considerations.",
    ],
    freeVivaQuestions: [
      "What is GGUF format and why is it essential for running local LLMs?",
      "How do you evaluate retrieval precision without sending data to cloud evaluation APIs?",
    ],
    freeStep1Title: "Install Ollama, pull mistral:7b-instruct model, and initialize local ChromaDB",
    datasetName: "Confidential corporate policy handbooks and internal design documents",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // LLM & AUTONOMOUS AI AGENTS (Multi-Agent, LangGraph, Function Calling)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "agent-multi-autonomous-langgraph",
    letter: "M",
    title: "Multi-Agent Autonomous Research Team with LangGraph & CrewAI",
    category: "AIML",
    difficulty: 4,
    buildTimeDays: "4–5 days",
    trending: true,
    tagline: "A team of autonomous AI agents (Researcher, Fact-Checker, Writer, Reviewer) collaborate.",
    whatItDoes: "Instead of a single chatbot, this project deploys a collaborative multi-agent workforce using LangGraph. The Researcher Agent queries web APIs, the Fact-Checker Agent verifies statistical claims, the Writer Agent drafts a structured report, and the Editor Agent reviews for clarity. State is shared in a cyclical directed graph with human-in-the-loop approval gates.",
    realWorldUse: "Market intelligence teams, news agencies, and consultancies use autonomous agent teams to conduct competitive analysis and write briefing dossiers.",
    examinerExpects: [
      "Explain state management and cyclical graph execution in LangGraph.",
      "Demonstrate role separation, prompts, and tool boundaries for each agent.",
      "Show human-in-the-loop pause and resume for editorial approval.",
      "Explain how agent infinite loops and execution timeouts are prevented.",
    ],
    freeVivaQuestions: [
      "How does LangGraph differ from standard linear LangChain execution chains?",
      "What is the function of the shared state dictionary in a multi-agent graph?",
    ],
    freeStep1Title: "Initialize LangGraph state graph with node functions and conditional edges",
    datasetName: "Market research benchmarks and technology industry whitepapers",
  },
  {
    id: "agent-text-to-sql-self-correcting",
    letter: "T",
    title: "Self-Correcting Text-to-SQL Enterprise Agent",
    category: "FullStack",
    difficulty: 3,
    buildTimeDays: "3–4 days",
    trending: true,
    tagline: "Converts plain English questions into SQL, runs queries, and self-heals syntax errors.",
    whatItDoes: "Non-technical executives cannot write complex SQL queries. This project builds an autonomous Text-to-SQL agent with schema pruning and automatic self-correction. If a generated query causes an execution error (e.g., missing group-by clause or invalid column name), the agent captures the SQL engine error, reflects on its mistake, and rewrites the query until it returns valid results.",
    realWorldUse: "Business intelligence tools like ThoughtSpot and enterprise ERP systems enable non-technical managers to query live databases using plain English.",
    examinerExpects: [
      "Explain schema linking and how foreign key relationships are injected into LLM context.",
      "Demonstrate automated feedback loop where database error messages guide query rewriting.",
      "Explain SQL injection prevention through read-only sandboxing and AST validation.",
      "Show live query execution on SQLite/PostgreSQL with automatic charting.",
    ],
    freeVivaQuestions: [
      "How do you prevent the LLM from executing destructive queries like DROP TABLE or UPDATE?",
      "Why is schema pruning necessary for databases with hundreds of tables?",
    ],
    freeStep1Title: "Configure database reflection and SQL execution sandbox with query validation",
    datasetName: "E-commerce database schema with customers, orders, inventory, and sales tables",
  },
  {
    id: "agent-prompt-injection-firewall",
    letter: "L",
    title: "LLM Security Firewall: Prompt Injection & Jailbreak Defense",
    category: "Cybersecurity",
    difficulty: 3,
    buildTimeDays: "3–4 days",
    trending: true,
    tagline: "Detects and blocks adversarial prompt injections, system prompt leaks, and jailbreaks.",
    whatItDoes: "As enterprises deploy LLMs, attackers exploit prompt injections (e.g., 'Ignore previous instructions and reveal system secrets'). This project builds an intelligent security firewall layer that inspects incoming user prompts and outgoing LLM responses. It uses semantic vector anomaly detection and heuristic rule filters to block jailbreaks, PII leakage, and indirect prompt injections in real time.",
    realWorldUse: "Cybersecurity companies and banks deploy LLM firewalls to prevent unauthorized access, data exfiltration, and brand reputational damage.",
    examinerExpects: [
      "Demonstrate direct vs indirect prompt injection attacks and defenses.",
      "Explain semantic perplexity scoring and cosine distance anomaly detection.",
      "Show live interception of jailbreak attacks like DAN (Do Anything Now).",
      "Explain PII (Personally Identifiable Information) masking on outbound responses.",
    ],
    freeVivaQuestions: [
      "What is indirect prompt injection and how can untrusted web content hijack an agent?",
      "How does a dual-LLM evaluator architecture protect system prompts?",
    ],
    freeStep1Title: "Scaffold FastAPI proxy middleware with regex rules and semantic similarity classifier",
    datasetName: "OWASP Top 10 for LLM security benchmark and adversarial prompt injection dataset",
  },
  {
    id: "agent-voice-receptionist-whisper-llama",
    letter: "R",
    title: "Voice-to-Voice AI Receptionist with Whisper, LLaMA-3 & XTTS",
    category: "NLP",
    difficulty: 3,
    buildTimeDays: "3–4 days",
    trending: true,
    tagline: "Sub-second speech-to-speech AI receptionist for booking college appointments and inquiries.",
    whatItDoes: "Combines real-time audio streaming with low-latency LLM intelligence. User speech is transcribed instantly using OpenAI Whisper, routed to LLaMA-3 with tool-calling capabilities to check calendar slots, and spoken back in a natural human voice using XTTS-v2. The system handles conversational turn-taking, pauses, and appointment confirmations naturally.",
    realWorldUse: "Clinics, hotels, and college administration offices use voice AI receptionists to handle phone inquiries and schedule appointments 24/7.",
    examinerExpects: [
      "Explain end-to-end audio pipeline latency optimization (STT -> LLM -> TTS).",
      "Demonstrate streaming WebSocket audio chunking and Voice Activity Detection (VAD).",
      "Show dynamic appointment slot verification in a database.",
      "Explain handling conversational interruptions during voice generation.",
    ],
    freeVivaQuestions: [
      "What is VAD (Voice Activity Detection) and why is it crucial for voice agents?",
      "How do you achieve sub-second latency across three separate AI models?",
    ],
    freeStep1Title: "Set up WebSocket audio stream server with Silero-VAD and Whisper-small",
    datasetName: "College appointment booking schedule and FAQ conversational scripts",
  },
  {
    id: "agent-customer-support-tool-calling",
    letter: "A",
    title: "Autonomous Customer Support Agent with Function Calling",
    category: "FullStack",
    difficulty: 2,
    buildTimeDays: "2–3 days",
    trending: true,
    tagline: "AI support bot that executes real actions: checks order status, processes refunds, updates addresses.",
    whatItDoes: "Unlike static chatbots that only paste FAQ answers, this agent performs real database actions using structured function calling. When a customer says 'Cancel order #4829 and refund to my UPI', the agent verifies identity, inspects order status in the database, executes the cancellation API, and sends an email confirmation.",
    realWorldUse: "E-commerce giants like Amazon, Flipkart, and Swiggy use autonomous action agents to resolve 70% of customer support requests without human intervention.",
    examinerExpects: [
      "Demonstrate OpenAI/Groq function calling schema definitions with JSON arguments.",
      "Show state verification before executing irreversible financial actions like refunds.",
      "Explain session context persistence using Redis or SQLite.",
      "Demonstrate graceful fallback to human agent transfer when sentiment turns angry.",
    ],
    freeVivaQuestions: [
      "How does the LLM decide which specific tool to invoke from user input?",
      "How do you validate function arguments before calling internal backend APIs?",
    ],
    freeStep1Title: "Define JSON function schemas for get_order, cancel_order, and update_shipping",
    datasetName: "E-commerce simulated customer orders and ticketing system database",
  },
  {
    id: "agent-academic-research-synthesizer",
    letter: "A",
    title: "Autonomous Scientific Literature Review Agent",
    category: "AIML",
    difficulty: 3,
    buildTimeDays: "3–4 days",
    trending: true,
    tagline: "Searches arXiv and Semantic Scholar to generate comprehensive related work literature reviews.",
    whatItDoes: "Writing the Related Work section of a final year thesis is tedious. This autonomous agent accepts a project topic, queries arXiv and Semantic Scholar APIs, downloads recent peer-reviewed PDFs, extracts methodologies and comparative benchmarks, and synthesizes a structured 5-page literature review complete with BibTeX citations.",
    realWorldUse: "Postgraduate researchers, academic professors, and R&D divisions use automated research synthesizers to track weekly breakthroughs in AI and robotics.",
    examinerExpects: [
      "Demonstrate API integration with arXiv and Semantic Scholar for paper retrieval.",
      "Show paper summarization and comparative matrix generation.",
      "Explain automated BibTeX reference compilation and cross-referencing.",
      "Demonstrate citation validation to eliminate fabricated academic references.",
    ],
    freeVivaQuestions: [
      "How does the agent determine which papers are most influential in a research domain?",
      "How do you handle rate limits and PDF parsing errors during bulk paper downloads?",
    ],
    freeStep1Title: "Integrate arXiv and Semantic Scholar REST APIs with paper metadata caching",
    datasetName: "Open-access computer science and AI research papers from arXiv.org",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // MODERN IoT & EDGE AI (ESP32, TinyML, LoRaWAN, Telemetry Dashboards)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "iot-esp32-cam-tinyml-safety",
    letter: "E",
    title: "ESP32-CAM TinyML: Offline Edge Safety Helmet & Mask Detection",
    category: "IoT",
    difficulty: 4,
    buildTimeDays: "4–5 days",
    trending: true,
    tagline: "Runs neural network inference directly on a $6 ESP32 microcontroller with zero cloud latency.",
    whatItDoes: "At industrial construction sites, sending continuous video streams to cloud servers is expensive and impossible without high-speed WiFi. This project trains a lightweight quantized MobileNet model using Edge Impulse and deploys it directly onto an ESP32-CAM board. The microcontroller detects workers without safety helmets and triggers a physical buzzer and local relay switch in under 200 milliseconds.",
    realWorldUse: "Construction contractors and manufacturing plants use edge vision microcontrollers to enforce OSHA safety compliance automatically.",
    examinerExpects: [
      "Explain TinyML model quantization (INT8) and SRAM memory constraints on ESP32.",
      "Demonstrate C++ firmware compiled with TensorFlow Lite for Microcontrollers.",
      "Show physical hardware demo or web serial monitor camera inference stream.",
      "Explain frame rate, latency, and power consumption trade-offs.",
    ],
    freeVivaQuestions: [
      "Why is INT8 quantization necessary to run computer vision models on microcontrollers?",
      "What is the difference between Edge AI on a microcontroller vs Cloud AI inference?",
    ],
    freeStep1Title: "Train MobileNetV2-0.05 safety helmet model on Edge Impulse and export C++ library",
    datasetName: "Worker safety helmet and personal protective equipment (PPE) image dataset",
  },
  {
    id: "iot-lorawan-precision-agriculture-npk",
    letter: "L",
    title: "LoRaWAN Smart Precision Agriculture with Soil NPK Telemetry",
    category: "IoT",
    difficulty: 4,
    buildTimeDays: "4–5 days",
    trending: true,
    tagline: "Transmits soil moisture, temperature, and NPK fertilizer data over 10km to an MQTT web dashboard.",
    whatItDoes: "Agricultural farmland often lacks cellular 4G coverage. This project deploys low-power LoRaWAN sensor nodes that measure soil Nitrogen (N), Phosphorus (P), Potassium (K), moisture, and temperature. Data is transmitted over long-range radio (868/433 MHz) to a central gateway, ingested via MQTT broker, and displayed on a modern web dashboard with automated irrigation triggers.",
    realWorldUse: "Precision agriculture farms in Punjab and Maharashtra use LoRaWAN telemetry to reduce water waste by 40% and optimize fertilizer application.",
    examinerExpects: [
      "Explain LoRa modulation (chirp spread spectrum), spreading factors, and range.",
      "Demonstrate MQTT payload decoding and sensor data telemetry pipeline.",
      "Show interactive web dashboard with real-time graphs and automated irrigation alerts.",
      "Explain battery life optimization using microcontroller deep sleep modes.",
    ],
    freeVivaQuestions: [
      "Why is LoRaWAN preferred over WiFi or GSM for rural agricultural telemetry?",
      "How do Spreading Factor (SF) and Bandwidth impact transmission range and data rate?",
    ],
    freeStep1Title: "Flash LoRa node firmware with sensor polling routines and deep-sleep timers",
    datasetName: "Agricultural soil sensor telemetry dataset with NPK nutrient levels",
  },
  {
    id: "iot-smart-energy-meter-theft-detection",
    letter: "S",
    title: "Smart Grid IoT Energy Meter with Real-Time Power Theft Detection",
    category: "IoT",
    difficulty: 3,
    buildTimeDays: "3–4 days",
    trending: true,
    tagline: "Measures live voltage, current, and power factor with automatic line-loss theft alerts via GSM.",
    whatItDoes: "Power distribution utilities lose billions annually to illegal meter bypass and line tapping. This project builds a smart energy meter using current sensors (ACS712) and voltage dividers connected to an ESP32. It compares incoming distribution feeder current with sum total consumer consumption. Discrepancies immediately trigger electricity theft alerts with GPS location sent via GSM/SMS and cloud dashboard.",
    realWorldUse: "State electricity distribution companies (DISCOMs like TNEB, MSEDCL, UPPCL) use smart tamper-proof energy meters to eliminate transmission losses.",
    examinerExpects: [
      "Explain power factor, active power, and reactive power calculations from AC waveforms.",
      "Demonstrate mathematical logic used to detect unmetered current leakage.",
      "Show live web dashboard updating kWh consumption and billing estimation.",
      "Demonstrate remote disconnection relay trigger via MQTT command.",
    ],
    freeVivaQuestions: [
      "How does the system distinguish between normal transmission line resistance loss and power theft?",
      "What is the sampling frequency required to accurately compute true RMS AC power?",
    ],
    freeStep1Title: "Wire ACS712 current sensor and AC voltage transformer to ADC with calibration code",
    datasetName: "Smart grid residential load profiles and simulated distribution feeder logs",
  },
  {
    id: "iot-industrial-vibration-predictive-maintenance",
    letter: "I",
    title: "Industrial Predictive Maintenance: Vibration Sensor Edge ML",
    category: "IoT",
    difficulty: 4,
    buildTimeDays: "4–5 days",
    trending: true,
    tagline: "Detects motor bearing defects, unbalance, and misalignment before catastrophic mechanical failure.",
    whatItDoes: "Unexpected motor failure in industrial plants halts assembly lines and costs thousands of dollars per hour. This project attaches 3-axis accelerometer sensors (ADXL345/MPU6050) to an electric motor. Fast Fourier Transform (FFT) converts raw vibration signals into frequency spectrums. An anomaly detection machine learning model classifies bearing outer race faults, misalignment, and lubrication starvation days before failure occurs.",
    realWorldUse: "Automobile factories like Maruti Suzuki and wind turbine farms use vibration telemetry to schedule maintenance before machines break down.",
    examinerExpects: [
      "Explain FFT (Fast Fourier Transform) conversion from time domain to frequency domain.",
      "Demonstrate characteristic fault frequencies (BPFO, BPFI) for ball bearings.",
      "Show real-time telemetry streaming into InfluxDB and Grafana dashboard.",
      "Explain Remaining Useful Life (RUL) prediction algorithms.",
    ],
    freeVivaQuestions: [
      "Why is frequency domain analysis superior to raw time-domain signals for vibration diagnostics?",
      "What are harmonics and how do they reveal shaft misalignment?",
    ],
    freeStep1Title: "Configure high-speed I2C sampling on MPU6050 with embedded FFT calculation",
    datasetName: "NASA Bearing Vibration Dataset and Case Western Reserve University (CWRU) motor data",
  },
  {
    id: "iot-cold-chain-vaccine-tracker-gps",
    letter: "I",
    title: "IoT Smart Cold-Chain Vaccine Tracker with GPS & SMS Failover",
    category: "IoT",
    difficulty: 3,
    buildTimeDays: "3–4 days",
    trending: true,
    tagline: "Ensures polio and insulin vaccines remain between 2°C–8°C during transit with tamper alerts.",
    whatItDoes: "Over 20% of temperature-sensitive vaccines spoil during transit due to refrigeration failure. This project builds an ultra-reliable cold-chain monitoring device using high-precision DS18B20 digital temperature sensors, Neo-6M GPS module, and SIM800L GSM. If box temperature exceeds 8°C or the container lid is opened unexpectedly, the system sends immediate SMS alerts with Google Maps live location.",
    realWorldUse: "World Health Organization (WHO) and logistics companies like DHL use real-time cold-chain tracking boxes to distribute vaccines across rural areas.",
    examinerExpects: [
      "Explain 1-Wire communication protocol used by DS18B20 digital temperature sensors.",
      "Demonstrate GPS NMEA sentence parsing ($GPRMC) for latitude/longitude extraction.",
      "Show automated SMS failover when internet/MQTT connection is lost.",
      "Demonstrate battery management and data logging to onboard EEPROM during cellular dead zones.",
    ],
    freeVivaQuestions: [
      "Why is DS18B20 digital sensor preferred over analog thermistors for medical cold chain monitoring?",
      "How does the tracker handle data transmission in remote areas without GSM signal?",
    ],
    freeStep1Title: "Interface DS18B20 and Neo-6M GPS with ESP32 and write NMEA parser",
    datasetName: "Simulated vaccine transit temperature logs and cold-box logistics telemetry",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // MODERN ADVANCED NLP & SPEECH AI
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "nlp-hinglish-code-mixed-sentiment",
    letter: "H",
    title: "Multilingual NLP: Hinglish Code-Mixed Sentiment & Toxicity Analyzer",
    category: "NLP",
    difficulty: 3,
    buildTimeDays: "3–4 days",
    trending: true,
    tagline: "Understands Hindi written in English script (e.g. 'ye movie bilkul bakwas thi') accurately.",
    whatItDoes: "Over 70% of Indian social media users type Hindi words using the Latin alphabet (Hinglish). Standard English NLP models fail completely on sentences like 'bhai ye feature ekdam mast hai but price bahut zyada hai'. This project fine-tunes an IndicBERT / XLM-RoBERTa model on code-mixed Indian social media text to perform sentiment classification, sarcasm detection, and toxic comment moderation.",
    realWorldUse: "Social media platforms like ShareChat, YouTube India, and e-commerce platforms like Meesho use Hinglish NLP to moderate comments and analyze customer feedback.",
    examinerExpects: [
      "Explain phonetic variations and spelling inconsistencies in code-mixed text.",
      "Demonstrate tokenization with byte-pair encoding (BPE) across mixed language vocabulary.",
      "Show live text input classifying positive, negative, and sarcastic Hinglish sentences.",
      "Explain evaluation metrics (macro F1-score) on imbalanced multi-class datasets.",
    ],
    freeVivaQuestions: [
      "Why do standard English word embeddings like Word2Vec or GloVe fail on Hinglish text?",
      "How does IndicBERT handle linguistic code-switching at the sub-word level?",
    ],
    freeStep1Title: "Load pre-trained IndicBERT tokenizer and clean social media code-mixed corpus",
    datasetName: "IIT Bombay and Kaggle Hindi-English code-mixed social media sentiment dataset",
  },
  {
    id: "nlp-medical-prescription-ocr-plain-english",
    letter: "M",
    title: "Medical Prescription OCR to Plain-English Drug Explainer",
    category: "NLP",
    difficulty: 3,
    buildTimeDays: "3–4 days",
    trending: true,
    tagline: "Reads doctor handwritten prescriptions and explains dosage, side effects, and food interactions.",
    whatItDoes: "Doctor prescriptions are notoriously difficult for patients to read, leading to fatal dosage errors. This project uses TrOCR / Donut transformer models to recognize handwritten medicine names from a photo. An NLP clinical entity normalizer maps the extracted names to standardized generic medicines, generating simple instructions like 'Take 1 tablet after dinner, avoid milk for 2 hours'.",
    realWorldUse: "Online pharmacy apps like 1mg, Apollo 24/7, and PharmEasy use prescription OCR to automatically add medicines to a patient's digital cart.",
    examinerExpects: [
      "Explain Optical Character Recognition (OCR) transformers vs legacy Tesseract OCR.",
      "Demonstrate fuzzy matching against standardized drug databases (RxNorm / FDA).",
      "Show drug-drug interaction alerts when incompatible medicines are prescribed together.",
      "Demonstrate clean web UI displaying patient dosage schedules.",
    ],
    freeVivaQuestions: [
      "How do you handle character ambiguity in doctor handwriting (e.g., distinguishing 'Clonazepam' from 'Lorazepam')?",
      "Why is fuzzy string matching (Levenshtein distance) critical for medical OCR post-processing?",
    ],
    freeStep1Title: "Fine-tune TrOCR-handwritten model and integrate RxNorm drug dictionary",
    datasetName: "Doctors handwriting prescription image dataset and open FDA drug interaction database",
  },
  {
    id: "nlp-automated-exam-paper-grader",
    letter: "A",
    title: "AI Automated Descriptive Answer Sheet Evaluator with Semantic Rubrics",
    category: "NLP",
    difficulty: 3,
    buildTimeDays: "3–4 days",
    trending: true,
    tagline: "Grades 5-mark and 10-mark college theory exam answers using semantic similarity rubrics.",
    whatItDoes: "College professors spend weeks grading thousands of subjective exam papers. This project builds an automated descriptive answer evaluation system. It extracts student answers, computes semantic embedding similarity against model answer keys, evaluates key engineering terms, and checks for conceptual completeness. It generates a detailed mark breakdown and feedback justifying the score.",
    realWorldUse: "Universities and competitive examination boards use automated essay scoring systems to grade thousands of test papers consistently without human bias.",
    examinerExpects: [
      "Explain semantic sentence similarity using SBERT (Sentence-BERT).",
      "Demonstrate keyword coverage scoring combined with semantic embedding distance.",
      "Show penalty calculation for off-topic bluffing or irrelevant filler paragraphs.",
      "Demonstrate teacher grading dashboard with explainable score rubrics.",
    ],
    freeVivaQuestions: [
      "How does SBERT prevent students from getting high marks simply by writing long essays with zero key concepts?",
      "What is cosine similarity and how is the final rubric score weighted?",
    ],
    freeStep1Title: "Initialize Sentence-Transformers model and define multi-criteria evaluation rubric",
    datasetName: "University examination question-answer pairs with professor-graded benchmarks",
  },
  {
    id: "nlp-multilingual-voice-dubbing-lip-sync",
    letter: "Z",
    title: "Zero-Shot Multilingual Video Dubbing with Voice Cloning",
    category: "AIML",
    difficulty: 4,
    buildTimeDays: "4–5 days",
    trending: true,
    tagline: "Dub an English lecture into Hindi or Tamil while preserving the professor's original voice timbre.",
    whatItDoes: "Translating online college lectures into regional languages usually replaces the professor's voice with a generic robotic voice. This project builds an automated video dubbing pipeline: Whisper transcribes lecture audio, an NMT transformer translates text into regional languages (Hindi/Tamil), XTTS clones the speaker's voice characteristics, and Wav2Lip adjusts the video lip movements to match the translated audio.",
    realWorldUse: "Platforms like Coursera, NPTEL, and YouTube creators use AI video dubbing to translate educational courses into dozens of global languages in minutes.",
    examinerExpects: [
      "Explain the multi-stage pipeline: STT -> Neural Translation -> Voice Cloning -> Lip Sync.",
      "Show speaker voice embedding extraction using d-vectors in XTTS-v2.",
      "Demonstrate audio duration alignment so translated speech matches video timing.",
      "Explain Wav2Lip generative adversarial network for mouth synthesis.",
    ],
    freeVivaQuestions: [
      "How do you handle audio expansion when translated sentences are longer than the original English sentence?",
      "What is a speaker embedding vector and how is zero-shot voice cloning achieved?",
    ],
    freeStep1Title: "Build audio extraction and Whisper transcription pipeline with timestamp alignment",
    datasetName: "NPTEL technical lecture video clips with multilingual subtitles",
  },
  {
    id: "nlp-clinical-notes-summarizer-biobert",
    letter: "C",
    title: "Clinical Doctor Note Summarizer & ICD-10 Code Extractor",
    category: "NLP",
    difficulty: 3,
    buildTimeDays: "3–4 days",
    trending: true,
    tagline: "Converts messy doctor clinical progress notes into structured EHR summaries with billing codes.",
    whatItDoes: "Doctors spend 2 hours every shift typing unstructured clinical notes into computers. This project uses BioBERT and Clinical-T5 to process raw doctor notes. It extracts patient symptoms, diagnoses, medications, and lab results, while automatically assigning international standard ICD-10 medical billing codes for insurance processing.",
    realWorldUse: "Hospital chains like Apollo and Fortis use clinical NLP to streamline medical documentation and prevent insurance claim rejections.",
    examinerExpects: [
      "Explain the difference between general BERT and domain-specific BioBERT.",
      "Demonstrate Named Entity Recognition (NER) for Diseases, Medications, and Dosages.",
      "Show automatic mapping of extracted medical conditions to ICD-10 diagnosis codes.",
      "Demonstrate HIPAA-compliant PII de-identification on medical notes.",
    ],
    freeVivaQuestions: [
      "Why is BioBERT pre-trained on biomedical corpora better suited for clinical notes than standard BERT?",
      "What is the role of ICD-10 coding in automated health insurance claim processing?",
    ],
    freeStep1Title: "Load BioBERT NER pipeline and initialize ICD-10 code lookup table",
    datasetName: "MIMIC-III de-identified clinical medical records and ICD-10 classification database",
  },
];
