const fs = require('fs');
const { createClient } = require('@supabase/supabase-js');
require('dotenv').config({ path: '.env.local' });

const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY);

const projects = [
  // CYBERSECURITY (10)
  { slug: 'phishing-detector-ai', title: 'AI-Powered Phishing URL Detector', category: 'Cybersecurity', tier: 'MINI', price_inr: 299, description: 'Machine learning model that analyzes URL lexical features to detect zero-day phishing attacks.', tech_stack: ['Python', 'Random Forest', 'Flask', 'Chrome Extension'], features: ['URL feature extraction', 'Browser integration', 'Real-time scoring'], live_demo_url: 'https://ui.shadcn.com/examples/dashboard' },
  { slug: 'network-ids', title: 'Intrusion Detection System (IDS)', category: 'Cybersecurity', tier: 'MAJOR', price_inr: 499, description: 'Deep learning based network packet analyzer for detecting DDoS and port scanning attacks.', tech_stack: ['Python', 'Scapy', 'TensorFlow', 'React'], features: ['Live packet sniffing', 'Anomaly detection', 'Alert dashboard'], live_demo_url: 'https://ui.shadcn.com/examples/cards' },
  { slug: 'steganography-tool', title: 'Secure Steganography Vault', category: 'Cybersecurity', tier: 'MINI', price_inr: 299, description: 'Advanced image steganography tool to hide encrypted text data inside LSB of images.', tech_stack: ['Python', 'OpenCV', 'AES-256', 'Tkinter'], features: ['LSB Encoding', 'AES Encryption', 'Lossless compression'], live_demo_url: 'https://ui.shadcn.com/examples/tasks' },
  { slug: 'ransomware-sandbox', title: 'Ransomware Behavior Sandbox', category: 'Cybersecurity', tier: 'MAJOR', price_inr: 499, description: 'Isolated environment for detonating malware and logging file-system and registry modifications.', tech_stack: ['C++', 'Windows API', 'Python', 'React'], features: ['API Hooking', 'Behavioral analysis', 'Report generation'], live_demo_url: 'https://ui.shadcn.com/examples/dashboard' },
  { slug: 'keylogger-detector', title: 'Heuristic Keylogger Detector', category: 'Cybersecurity', tier: 'MINI', price_inr: 299, description: 'Detects unauthorized global keyboard hooks and warns users of potential spyware.', tech_stack: ['C#', '.NET', 'Windows Forms'], features: ['Hook detection', 'Process termination', 'Background scanning'], live_demo_url: 'https://ui.shadcn.com/examples/forms' },
  { slug: 'sql-injection-scanner', title: 'Automated SQLi Vulnerability Scanner', category: 'Cybersecurity', tier: 'MINI', price_inr: 299, description: 'Web crawler that injects payloads into inputs to detect SQL injection vulnerabilities.', tech_stack: ['Python', 'BeautifulSoup', 'Requests', 'SQLite'], features: ['Form crawling', 'Payload injection', 'PDF Reporting'], live_demo_url: 'https://ui.shadcn.com/examples/cards' },
  { slug: 'blockchain-identity', title: 'Decentralized Identity (DID) Auth', category: 'Cybersecurity', tier: 'MAJOR', price_inr: 499, description: 'Passwordless authentication system using Ethereum blockchain and verifiable credentials.', tech_stack: ['Solidity', 'Web3.js', 'Next.js', 'Node.js'], features: ['Zero-knowledge proofs', 'MetaMask login', 'Identity recovery'], live_demo_url: 'https://ui.shadcn.com/examples/music' },
  { slug: 'honey-pot-server', title: 'Deceptive Honeypot Server', category: 'Cybersecurity', tier: 'MAJOR', price_inr: 499, description: 'Simulated vulnerable SSH and FTP server to trap attackers and analyze their techniques.', tech_stack: ['Python', 'Twisted', 'Docker', 'Kibana'], features: ['Protocol simulation', 'Attack logging', 'IP geolocation mapping'], live_demo_url: 'https://ui.shadcn.com/examples/dashboard' },
  { slug: 'password-strength-nn', title: 'Neural Net Password Strength Analyzer', category: 'Cybersecurity', tier: 'MINI', price_inr: 299, description: 'RNN-based model that predicts password crackability time better than standard entropy checks.', tech_stack: ['Python', 'Keras', 'FastAPI', 'React'], features: ['Sequence modeling', 'Real-time feedback', 'Dictionary attack simulation'], live_demo_url: 'https://ui.shadcn.com/examples/tasks' },
  { slug: 'wifi-deauth-monitor', title: 'Wi-Fi Deauthentication Monitor', category: 'Cybersecurity', tier: 'MINI', price_inr: 299, description: 'Detects Wi-Fi deauth attacks (like those from ESP8266) and alerts the network admin.', tech_stack: ['Python', 'Scapy', 'Linux Aircrack-ng'], features: ['Packet monitoring', 'MAC spoof detection', 'SMS Alerts'], live_demo_url: 'https://ui.shadcn.com/examples/mail' },

  // IOT & EMBEDDED (10)
  { slug: 'smart-agriculture-iot', title: 'IoT Precision Agriculture System', category: 'IoT', tier: 'MAJOR', price_inr: 499, description: 'Soil moisture, NPK, and temperature monitoring with automated water pump control.', tech_stack: ['Arduino', 'ESP32', 'MQTT', 'React'], features: ['Real-time telemetry', 'Automated irrigation', 'Weather API integration'], live_demo_url: 'https://ui.shadcn.com/examples/dashboard' },
  { slug: 'iot-patient-monitor', title: 'IoT Remote Patient Monitoring', category: 'IoT', tier: 'MAJOR', price_inr: 499, description: 'Wearable simulation for heart rate and SpO2 monitoring with emergency cloud alerts.', tech_stack: ['NodeMCU', 'Firebase', 'Flutter', 'C++'], features: ['Vitals dashboard', 'Emergency thresholds', 'Doctor portal'], live_demo_url: 'https://ui.shadcn.com/examples/cards' },
  { slug: 'smart-parking-iot', title: 'IoT Smart Parking Allocation', category: 'IoT', tier: 'MINI', price_inr: 299, description: 'IR sensor based parking spot detection with a web dashboard for available slots.', tech_stack: ['ESP8266', 'Node.js', 'Socket.io', 'HTML/CSS'], features: ['Slot availability', 'Entry/Exit gate control', 'Live updates'], live_demo_url: 'https://ui.shadcn.com/examples/tasks' },
  { slug: 'rfid-toll-collection', title: 'Automated RFID Toll Collection', category: 'IoT', tier: 'MINI', price_inr: 299, description: 'RFID reader integration that automatically deducts balance from user accounts at tolls.', tech_stack: ['Arduino', 'RFID RC522', 'PHP', 'MySQL'], features: ['Balance deduction', 'Admin panel', 'Low balance alerts'], live_demo_url: 'https://ui.shadcn.com/examples/forms' },
  { slug: 'iot-garbage-bin', title: 'Smart City Garbage Bin Monitor', category: 'IoT', tier: 'MINI', price_inr: 299, description: 'Ultrasonic sensor integration to measure garbage fill levels and optimize collection routes.', tech_stack: ['ESP32', 'Ultrasonic HC-SR04', 'Google Maps API'], features: ['Fill level percentage', 'Route optimization', 'City dashboard'], live_demo_url: 'https://ui.shadcn.com/examples/dashboard' },
  { slug: 'home-automation-voice', title: 'Voice-Controlled Home Automation', category: 'IoT', tier: 'MINI', price_inr: 299, description: 'Control home appliances using Google Assistant/Alexa webhooks and an ESP8266.', tech_stack: ['ESP8266', 'IFTTT', 'Adafruit IO', 'Relay Modules'], features: ['Voice commands', 'Manual override web UI', 'Power scheduling'], live_demo_url: 'https://ui.shadcn.com/examples/cards' },
  { slug: 'iot-energy-meter', title: 'Smart Energy Metering System', category: 'IoT', tier: 'MAJOR', price_inr: 499, description: 'Measures AC voltage/current and calculates power consumption, displaying costs in real-time.', tech_stack: ['ESP32', 'PZEM-004T', 'InfluxDB', 'Grafana'], features: ['Power tracking', 'Cost estimation', 'Overload cutoff'], live_demo_url: 'https://ui.shadcn.com/examples/music' },
  { slug: 'iot-weather-station', title: 'Microclimate Weather Station', category: 'IoT', tier: 'MINI', price_inr: 299, description: 'Local weather station measuring temp, humidity, pressure, and air quality (AQI).', tech_stack: ['Arduino', 'BME280', 'MQ135', 'ThingSpeak'], features: ['Data logging', 'AQI calculation', 'Historical graphs'], live_demo_url: 'https://ui.shadcn.com/examples/dashboard' },
  { slug: 'rfid-attendance-iot', title: 'IoT RFID Attendance System', category: 'IoT', tier: 'MINI', price_inr: 299, description: 'Tap-in attendance system that logs entries directly to a cloud Google Sheet.', tech_stack: ['NodeMCU', 'RFID', 'Google Apps Script'], features: ['Direct to Excel', 'Buzzer feedback', 'Duplicate scan prevention'], live_demo_url: 'https://ui.shadcn.com/examples/tasks' },
  { slug: 'iot-fall-detector', title: 'Elderly Fall Detection Wearable', category: 'IoT', tier: 'MAJOR', price_inr: 499, description: 'MPU6050 accelerometer based system to detect sudden falls and send SMS alerts.', tech_stack: ['ESP32', 'MPU6050', 'Twilio API', 'React Native'], features: ['Fall algorithm', 'GPS location', 'SMS emergency alert'], live_demo_url: 'https://ui.shadcn.com/examples/mail' },

  // DATA SCIENCE & ML (10)
  { slug: 'stock-predictor-lstm', title: 'Stock Market Predictor (LSTM)', category: 'DataScience', tier: 'MAJOR', price_inr: 499, description: 'Time-series forecasting using Long Short-Term Memory neural networks on historical Yahoo Finance data.', tech_stack: ['Python', 'Keras', 'LSTM', 'Streamlit'], features: ['Candlestick charts', 'Future trend prediction', 'Moving averages'], live_demo_url: 'https://ui.shadcn.com/examples/dashboard' },
  { slug: 'credit-card-fraud', title: 'Credit Card Fraud Detection', category: 'DataScience', tier: 'MINI', price_inr: 299, description: 'Anomaly detection using Random Forest and SMOTE for highly imbalanced dataset classification.', tech_stack: ['Python', 'Scikit-Learn', 'Pandas', 'Dash'], features: ['SMOTE balancing', 'Precision-Recall curves', 'Live transaction simulation'], live_demo_url: 'https://ui.shadcn.com/examples/cards' },
  { slug: 'customer-churn-ml', title: 'Telecom Customer Churn Predictor', category: 'DataScience', tier: 'MINI', price_inr: 299, description: 'Predicts which customers will leave a service based on usage patterns and billing data.', tech_stack: ['Python', 'XGBoost', 'Flask', 'Chart.js'], features: ['Feature importance', 'Probability scoring', 'Retention recommendations'], live_demo_url: 'https://ui.shadcn.com/examples/tasks' },
  { slug: 'movie-recommender', title: 'Collaborative Movie Recommender', category: 'DataScience', tier: 'MINI', price_inr: 299, description: 'Recommendation engine using cosine similarity and matrix factorization on the MovieLens dataset.', tech_stack: ['Python', 'Surprise Library', 'React'], features: ['User-based filtering', 'Item-based filtering', 'Cold-start handling'], live_demo_url: 'https://ui.shadcn.com/examples/forms' },
  { slug: 'pneumonia-xray-cnn', title: 'Pneumonia Detection from X-Rays', category: 'AIML', tier: 'MAJOR', price_inr: 499, description: 'Convolutional Neural Network (CNN) to classify chest X-ray images as Normal or Pneumonia.', tech_stack: ['Python', 'TensorFlow', 'OpenCV', 'Next.js'], features: ['Image augmentation', 'Grad-CAM visualization', 'High accuracy'], live_demo_url: 'https://ui.shadcn.com/examples/dashboard' },
  { slug: 'twitter-sentiment-analysis', title: 'Real-time Twitter Sentiment Analysis', category: 'DataScience', tier: 'MAJOR', price_inr: 499, description: 'Streams live tweets using API and classifies them as positive, negative, or neutral using NLP.', tech_stack: ['Python', 'NLTK', 'Tweepy', 'Grafana'], features: ['Live streaming', 'Emotion classification', 'Word clouds'], live_demo_url: 'https://ui.shadcn.com/examples/music' },
  { slug: 'house-price-prediction', title: 'Real Estate Price Predictor', category: 'DataScience', tier: 'MINI', price_inr: 299, description: 'Multiple linear regression model that predicts house prices based on location, area, and amenities.', tech_stack: ['Python', 'Scikit-Learn', 'Streamlit'], features: ['Interactive inputs', 'Model evaluation metrics', 'Map visualization'], live_demo_url: 'https://ui.shadcn.com/examples/cards' },
  { slug: 'sign-language-translator', title: 'Sign Language to Text Translator', category: 'AIML', tier: 'MAJOR', price_inr: 499, description: 'Uses MediaPipe hand tracking and LSTMs to translate live ASL sign language gestures into text.', tech_stack: ['Python', 'MediaPipe', 'Keras', 'React'], features: ['Live webcam feed', 'Dynamic gesture recognition', 'Text-to-speech'], live_demo_url: 'https://ui.shadcn.com/examples/dashboard' },
  { slug: 'spam-classifier-nlp', title: 'SMS Spam Classifier (NLP)', category: 'AIML', tier: 'MINI', price_inr: 299, description: 'Naive Bayes classifier using TF-IDF vectorization to detect spam SMS messages.', tech_stack: ['Python', 'Scikit-Learn', 'NLTK', 'Flask'], features: ['TF-IDF Vectorizer', 'Confusion matrix', 'Instant text analysis'], live_demo_url: 'https://ui.shadcn.com/examples/tasks' },
  { slug: 'driver-drowsiness-alert', title: 'Driver Drowsiness Detection', category: 'AIML', tier: 'MAJOR', price_inr: 499, description: 'Tracks Eye Aspect Ratio (EAR) using dlib to detect if a driver is falling asleep and sounds an alarm.', tech_stack: ['Python', 'OpenCV', 'dlib', 'Pygame'], features: ['Facial landmark detection', 'EAR calculation', 'Audio alerts'], live_demo_url: 'https://ui.shadcn.com/examples/mail' },

  // WEB3 & BLOCKCHAIN (10)
  { slug: 'nft-marketplace', title: 'Decentralized NFT Marketplace', category: 'FullStack', tier: 'MAJOR', price_inr: 499, description: 'Full-stack Web3 application for minting, buying, and selling ERC-721 tokens (NFTs).', tech_stack: ['Solidity', 'Next.js', 'Ethers.js', 'IPFS'], features: ['IPFS Image Hosting', 'Smart contract escrow', 'Wallet integration'], live_demo_url: 'https://ui.shadcn.com/examples/dashboard' },
  { slug: 'supply-chain-blockchain', title: 'Blockchain Supply Chain Tracker', category: 'FullStack', tier: 'MAJOR', price_inr: 499, description: 'Tracks the provenance of pharmaceutical drugs from manufacturer to patient using Ethereum.', tech_stack: ['Solidity', 'React', 'Truffle', 'Node.js'], features: ['Product lifecycle tracking', 'QR code scanning', 'Immutable ledger'], live_demo_url: 'https://ui.shadcn.com/examples/cards' },
  { slug: 'crypto-crowdfunding', title: 'Web3 Crowdfunding Platform', category: 'FullStack', tier: 'MAJOR', price_inr: 499, description: 'Kickstarter clone where backers fund projects using ETH. Funds are released via milestone voting.', tech_stack: ['Solidity', 'Hardhat', 'Next.js', 'TailwindCSS'], features: ['Milestone voting', 'Refund mechanism', 'Campaign creation'], live_demo_url: 'https://ui.shadcn.com/examples/tasks' },
  { slug: 'dapp-staking', title: 'DeFi Staking DApp', category: 'FullStack', tier: 'MAJOR', price_inr: 499, description: 'Users stake their ERC-20 tokens to earn yield over time based on smart contract logic.', tech_stack: ['Solidity', 'React', 'Web3.js'], features: ['Yield farming math', 'Token minting', 'Staking dashboard'], live_demo_url: 'https://ui.shadcn.com/examples/forms' },
  { slug: 'fake-product-identification', title: 'Fake Product Identification Web3', category: 'FullStack', tier: 'MAJOR', price_inr: 499, description: 'Consumers verify luxury product authenticity by checking its cryptographic signature on the blockchain.', tech_stack: ['Solidity', 'React Native', 'Ethers.js'], features: ['NFC/QR pairing', 'Ownership transfer', 'Counterfeit prevention'], live_demo_url: 'https://ui.shadcn.com/examples/dashboard' },
  { slug: 'decentralized-cloud-storage', title: 'Web3 Dropbox (IPFS)', category: 'FullStack', tier: 'MAJOR', price_inr: 499, description: 'A decentralized file storage application using IPFS and smart contracts for access control.', tech_stack: ['IPFS', 'Solidity', 'React', 'Pinata'], features: ['File encryption', 'IPFS pinning', 'Access management'], live_demo_url: 'https://ui.shadcn.com/examples/music' },
  { slug: 'blockchain-land-registry', title: 'Blockchain Land Registry System', category: 'FullStack', tier: 'MAJOR', price_inr: 499, description: 'Government portal to register land titles on a blockchain, preventing property fraud.', tech_stack: ['Solidity', 'React', 'Node.js', 'MongoDB'], features: ['Title transfer', 'Govt inspector approval', 'Immutable records'], live_demo_url: 'https://ui.shadcn.com/examples/dashboard' },
  { slug: 'web3-freelance-platform', title: 'Decentralized Freelance Platform', category: 'FullStack', tier: 'MAJOR', price_inr: 499, description: 'Upwork clone where payments are locked in an Ethereum smart contract escrow until work is delivered.', tech_stack: ['Solidity', 'Next.js', 'The Graph'], features: ['Escrow contracts', 'Dispute resolution', 'Gasless transactions'], live_demo_url: 'https://ui.shadcn.com/examples/cards' },
  { slug: 'crypto-portfolio-tracker', title: 'Crypto Portfolio Tracker', category: 'FullStack', tier: 'MINI', price_inr: 299, description: 'Web app that connects to Binance/CoinGecko APIs to track user crypto holdings and PnL.', tech_stack: ['React', 'Node.js', 'CoinGecko API', 'Chart.js'], features: ['Live price feeds', 'Profit/Loss graphs', 'Portfolio distribution'], live_demo_url: 'https://ui.shadcn.com/examples/tasks' },
  { slug: 'blockchain-notary', title: 'Blockchain Document Notary', category: 'FullStack', tier: 'MINI', price_inr: 299, description: 'Hashes a digital document (PDF) and stores the hash on the blockchain to prove existence at a specific time.', tech_stack: ['Solidity', 'React', 'SHA-256'], features: ['Document hashing', 'Timestamping', 'Verification portal'], live_demo_url: 'https://ui.shadcn.com/examples/mail' },

  // FULLSTACK / CLOUD / OTHER (10)
  { slug: 'alumni-networking-portal', title: 'College Alumni Networking Portal', category: 'FullStack', tier: 'MAJOR', price_inr: 499, description: 'A LinkedIn-like platform exclusive to college alumni for job referrals, events, and mentorship.', tech_stack: ['React', 'Node.js', 'MongoDB', 'Socket.io'], features: ['Job boards', 'Real-time chat', 'Event management', 'Donation portal'], live_demo_url: 'https://ui.shadcn.com/examples/dashboard' },
  { slug: 'online-code-compiler', title: 'Cloud Remote Code Compiler', category: 'FullStack', tier: 'MAJOR', price_inr: 499, description: 'Leetcode-like web IDE that executes C++, Java, and Python code in isolated Docker containers.', tech_stack: ['React', 'Node.js', 'Docker', 'Redis'], features: ['Code execution', 'Sandboxing', 'Syntax highlighting'], live_demo_url: 'https://ui.shadcn.com/examples/cards' },
  { slug: 'blood-bank-management', title: 'Smart Blood Bank Management', category: 'FullStack', tier: 'MINI', price_inr: 299, description: 'Connects blood donors directly with recipients and tracks blood inventory in hospitals.', tech_stack: ['PHP', 'Laravel', 'MySQL', 'Bootstrap'], features: ['Donor geolocation', 'Inventory tracking', 'Emergency alerts'], live_demo_url: 'https://ui.shadcn.com/examples/tasks' },
  { slug: 'virtual-try-on', title: 'AR Virtual Glasses Try-On', category: 'AIML', tier: 'MAJOR', price_inr: 499, description: 'Augmented Reality web app that uses facial landmarks to overlay 3D glasses on the user face.', tech_stack: ['React', 'Three.js', 'MediaPipe', 'WebRTC'], features: ['Facial tracking', '3D model rendering', 'Snapshot feature'], live_demo_url: 'https://ui.shadcn.com/examples/forms' },
  { slug: 'restaurant-qr-ordering', title: 'QR Code Restaurant Ordering', category: 'FullStack', tier: 'MINI', price_inr: 299, description: 'Customers scan a QR code on the table to view the digital menu and place orders to the kitchen.', tech_stack: ['Next.js', 'Firebase', 'TailwindCSS'], features: ['Digital menu', 'Kitchen display system', 'Bill calculation'], live_demo_url: 'https://ui.shadcn.com/examples/dashboard' },
  { slug: 'plagiarism-checker-tool', title: 'Document Plagiarism Checker', category: 'FullStack', tier: 'MINI', price_inr: 299, description: 'Compares uploaded text against web search results using Cosine Similarity and Jaccard distance.', tech_stack: ['Python', 'Flask', 'NLTK', 'Google Search API'], features: ['Web scraping', 'Similarity score', 'Highlighted copied text'], live_demo_url: 'https://ui.shadcn.com/examples/music' },
  { slug: 'task-management-kanban', title: 'Agile Kanban Task Manager', category: 'FullStack', tier: 'MINI', price_inr: 299, description: 'Trello clone with drag-and-drop boards, task assignments, and team collaboration.', tech_stack: ['React', 'Node.js', 'MongoDB', 'React-Beautiful-DnD'], features: ['Drag and drop', 'Role management', 'Deadline notifications'], live_demo_url: 'https://ui.shadcn.com/examples/dashboard' },
  { slug: 'e-learning-lms', title: 'E-Learning Course Platform', category: 'FullStack', tier: 'MAJOR', price_inr: 499, description: 'Udemy clone where instructors upload video courses and students track learning progress.', tech_stack: ['Next.js', 'PostgreSQL', 'AWS S3', 'Stripe'], features: ['Video streaming', 'Progress tracking', 'Certificate generation'], live_demo_url: 'https://ui.shadcn.com/examples/cards' },
  { slug: 'bug-tracking-system', title: 'Enterprise Bug Tracking System', category: 'FullStack', tier: 'MAJOR', price_inr: 499, description: 'Jira clone for software teams to log, assign, and track the status of software bugs.', tech_stack: ['Vue.js', 'Express', 'MySQL', 'Redis'], features: ['Issue logging', 'Priority levels', 'Developer dashboards'], live_demo_url: 'https://ui.shadcn.com/examples/tasks' },
  { slug: 'real-estate-bidding', title: 'Real Estate Auction & Bidding', category: 'FullStack', tier: 'MAJOR', price_inr: 499, description: 'Platform for auctioning properties with live WebSocket bidding and virtual property tours.', tech_stack: ['React', 'Node.js', 'Socket.io', 'PostgreSQL'], features: ['Live bidding', 'Virtual tour integration', 'Agent dashboard'], live_demo_url: 'https://ui.shadcn.com/examples/mail' }
];

async function seed() {
  const insertData = projects.map(p => ({
    ...p,
    s3_storage_key: `bundles/${p.tier.toLowerCase()}/${p.slug}.zip`,
    report_template_key: `templates/${p.tier.toLowerCase()}/${p.slug}-report.docx`,
  }));

  const { data, error } = await supabase.from('projects').upsert(insertData, { onConflict: 'slug' });
  if (error) {
    console.error('Error inserting data:', error);
  } else {
    console.log(`Successfully inserted ${projects.length} amazing projects!`);
  }

  // Generate the SQL string to append to seed.sql
  let sqlString = "\n\n-- BATCH OF 50 NEW PROJECTS\nINSERT INTO projects (slug, title, category, tier, price_inr, description, tech_stack, features, live_demo_url, s3_storage_key, report_template_key)\nVALUES \n";
  
  const sqlValues = insertData.map(p => {
    return `(
    '${p.slug}',
    '${p.title.replace(/'/g, "''")}',
    '${p.category}',
    '${p.tier}',
    ${p.price_inr},
    '${p.description.replace(/'/g, "''")}',
    ARRAY[${p.tech_stack.map(t => `'${t}'`).join(', ')}],
    ARRAY[${p.features.map(f => `'${f}'`).join(', ')}],
    '${p.live_demo_url}',
    '${p.s3_storage_key}',
    '${p.report_template_key}'
)`;
  });

  sqlString += sqlValues.join(',\n') + "\nON CONFLICT (slug) DO NOTHING;\n";

  fs.appendFileSync('supabase/seed.sql', sqlString);
  console.log('Appended SQL to supabase/seed.sql');
}

seed();
